# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffb40b60d5969a99c75dc52f312e5fbaf77d1844b24a53a2bd38e19f328468a7de86a5554a80f27e8a8899d2ad702f6a8c3dea18617cd1ea9847db06f8e483b0

test:
  secret_key_base: 47a00a5588ab9949f77b18baaad0c609bbc7e969bf378c53bcdd2515492f16ab88f53d618c893e7cd3a1096a6e5a6ba939fa43b8bb86f747f956a42efaa74f58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
